@echo off
echo Menginstal Leaflet...
call npm install leaflet react-leaflet leaflet-defaulticon-compatibility --legacy-peer-deps
echo Menginstal tipe data...
call npm install -D @types/leaflet --legacy-peer-deps
echo Menerapkan database...
call npx prisma db push
echo Selesai!
